### ISSUE TITLE
Do you need help maintaining this?

### ISSUE THREAD

**Issue by dploeger** [mkoertgen/azure-app-exporter#14]
We're using this app in our production system now to alert us of apps with credentials that are expiring.

Am I right, that you're not actively maintaining this currently? We're open to help you or even adopt the app. 🙂

**Comment by mkoertgen** [comment]
You are right @dploeger. As of now, I am not using the app on any production system and I also lack the spare time to update it accordingly and in a timely manner.

How would you suggest on adopting the app? 

1. Simplest for you would probably to just fork it
2. Next would be to add you as a co-owner
3. Better would be to move it to a separate gh-organization and have both of us as owners / contributors

**Comment by dploeger** [comment]
I'm part of the dodevops organization which we use to maintain our own open source projects and adopt others. I've added you as an admin to our fork of this. Would that be enough for you?

**Comment by mkoertgen** [comment]
Suits me fine 👍

I will archive this repo here and point to the fork at: https://github.com/dodevops/azure-app-exporter

**Comment by dploeger** [comment]
Awesome. I will prepare another release over at our place and then also publish the chart at Artifacthub.

**Comment by dploeger** [comment]
@mkoertgen Could you please transfer the ownership at Artifacthub? I've updated the files in the forked repository and created a new chart, but I'd like to update Artifacthub as well. 🙂
