### ISSUE TITLE
Adoption progress

### ISSUE THREAD

**Issue by dploeger** [mkoertgen/azure-app-exporter#18]
Hey, @mkoertgen. After we've adopted the exporter over at dodevops, could you please transfer the helm chart at artifacthub to the dodevops organization?

I've sent an invite, but actually it would be easier if you could just switch the repository URL to the new URL. Then we can claim ownership.

Thanks in advance!

**Comment by mkoertgen** [comment]
Hi @dploeger ,

Just tried transferring the package organization. Unfortunately ran into a 403. Will retry again later this day.

**Comment by mkoertgen** [comment]
Transfer succeeded. Also archived this repository and left an adoption note in the README.  Cheers 🍻
