### ISSUE TITLE
azure-app-exporter - Azure Kubernetes setup - Internal Server Error

### ISSUE THREAD

**Issue by jaisegrg** [mkoertgen/azure-app-exporter#3]
Hi @mkoertgen
<img width="901" alt="health" src="https://user-images.githubusercontent.com/69203235/170017582-18e7b223-88ca-4c30-8b93-173bf5ab0951.PNG">
<img width="922" alt="appget_internal_server_error" src="https://user-images.githubusercontent.com/69203235/170017597-07fadc07-256d-4254-b5c7-6f536a627c45.PNG">
[Pod_error.txt](https://github.com/mkoertgen/azure-app-exporter/files/8761930/Pod_error.txt)
,

I have setup "azure-app-exporter" using the helm chart and able to create deployments, service, servicemonitor in AKS cluster. Also able to view the Prometheus metrics. But, while accessing the AppID details using Swagger-UI at [/docs](http://localhost:8000/docs), it throws an internal server error. Screenshots and logs are attached for reference. 

Could you please help to resolve this issue?

**Comment by jaisegrg** [comment]
Hi @mkoertgen,

I have followed the steps to grant the service principal the API permissions "Application.ReadAll" to list other applications. Please refer to the attached screenshot. But, still i am getting "insufficient privileges" error while following the steps mentioned [#finalize](https://github.com/mkoertgen/azure-app-exporter/blob/main/_docs/service-principal.md#finalize), Is there any further steps to be executed to grant permission for the SP to list other applications?

Could you please look into this and suggest?
<img width="606" alt="SP_API_permissions" src="https://user-images.githubusercontent.com/69203235/170457794-5a8e72e9-7aec-472c-b92f-fc0bff96de8f.PNG">
<img width="768" alt="SP_verify_permissions" src="https://user-images.githubusercontent.com/69203235/170458176-4af08e7f-fe38-4585-bcec-0b0032a222bb.PNG">

**Comment by mkoertgen** [comment]
Hi @jaisegrg , 
The permissions look good, you should be fine.
Be sure to login with the created app/sp before checking the privileges. 
The state of Microsoft Graph + Azure AD is a bit unfortunate, making it quite hard to get SP right. Keep it up!

**Comment by jaisegrg** [comment]
@mkoertgen,

Yes, I logged in with the App/SP, still its throwing "internal server error". I am trying to implement in Azure Government Portal.

**Comment by mkoertgen** [comment]
Hi @jaisegrg ,

Another tip: Using the Azure CLI, try adding the `--debug` will print out the HTTP requests & responses, cf.:
- https://github.com/mkoertgen/azure-app-exporter/blob/main/_docs/references.md#azure-cli

This might help in resolving the issue. Especially the response for listing applications should be informative.

Note that https://github.com/mkoertgen/azure-app-exporter/blob/ae816e87083b3804dcec9f44cfc8d9fbef229dfe/src/services/azure_app_service.py#L28
is basically parsing one of the responses of `az ad sp credential list --id $AZURE_CLIENT_ID --debug`.

Maybe you can attach the (sanitized) logs?

**Comment by jaisegrg** [comment]
Hi @mkoertgen,

While executing the commands mentioned in [#finalize](https://github.com/mkoertgen/azure-app-exporter/blob/main/_docs/service-principal.md#finalize), I am getting proper results now.

# list application permissions
$ az ad app permission list --id $AZURE_CLIENT_ID
...
# login as app
$ az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
# and list applications including expiration dates
$ az ad app list --query "[].{appId:appId,credentials:passwordCredentials[].{name:customKeyIdentifier,created:startDate,expires:endDate}}"

Also, executed the command mentioned in https://github.com/mkoertgen/azure-app-exporter/blob/main/_docs/references.md#azure-cli and output looks fine. Please find the logs attached for reference.

But, still i am getting "Internal server error" while accessing the AppID details using Swagger-UI at [/docs](http://localhost:8000/docs).

Please find the attachments for more details. (metrics, Pod_logs, debug_output, docs_output)

<img width="896" alt="Get_all_apps" src="https://user-images.githubusercontent.com/69203235/175223348-3da304d0-92fa-4c7b-91b2-a461b7ed3bf5.PNG">
[debug_output.txt](https://github.com/mkoertgen/azure-app-exporter/files/8964294/debug_output.txt)
[metrics.txt](https://github.com/mkoertgen/azure-app-exporter/files/8964295/metrics.txt)
[Pod_logs.txt](https://github.com/mkoertgen/azure-app-exporter/files/8964296/Pod_logs.txt)

**Comment by jaisegrg** [comment]
@mkoertgen,

Could you please look into the issue?
