### ISSUE TITLE
Readiness probe errored: strconv.Atoi: parsing "http": invalid syntax

### ISSUE THREAD

**Issue by usamahzaheer** [mkoertgen/azure-app-exporter#4]
Hi, 
I am trying to deploy this exporter through the helm chart. It's giving me the following error
![image](https://user-images.githubusercontent.com/71088005/177733136-b2b96907-4da8-402b-a9c4-be5016d1d73c.png)
![image](https://user-images.githubusercontent.com/71088005/177733276-ecda2d0f-f60b-44ff-9276-c7a15ea22168.png)

**Comment by dploeger** [comment]
The deployment template is missing a "ports" definition. I've added that, but it still doesn't work. See #6

**Comment by mkoertgen** [comment]
Hi @dploeger,

The ports should be auto-detected using the exposed container ports, it is also using the named ports from the service. 
Will look into it.

**Comment by dploeger** [comment]
Really? Never saw that before. Okay.
