### ISSUE TITLE
Error on finalize step

### ISSUE THREAD

**Issue by noway75** [mkoertgen/azure-app-exporter#5]
`az ad app permission list --id $AZURE_CLIENT_ID
[
  {
    "resourceAccess": [
      {
        "id": "3afa6a7d-9b1a-42eb-948e-1650a849e176",
        "type": "Role"
      },
      {
        "id": "1cda74f2-2616-4834-b122-5cb1b07f8a59",
        "type": "Role"
      },
      {
        "id": "824c81eb-e3f8-4ee6-8f6d-de7f50d565b7",
        "type": "Role"
      },
      {
        "id": "5778995a-e1bf-45b8-affa-663a9f3f4d04",
        "type": "Role"
      }
    ],
    "resourceAppId": "00000002-0000-0000-c000-000000000000"
  },
  {
    "resourceAccess": [
      {
        "id": "e1fe6dd8-ba31-4d61-89e7-88639da4683d",
        "type": "Scope"
      },
      {
        "id": "18a4783c-866b-4cc7-a460-3d5e5662c884",
        "type": "Role"
      },
      {
        "id": "1bfefb4e-e0b5-418b-a88f-73c46d2cc8e9",
        "type": "Role"
      },
      {
        "id": "7ab1d382-f21e-4acd-a863-ba3e13f7da61",
        "type": "Role"
      },
      {
        "id": "9a5d68dd-52b0-4cc2-bd40-abcf44ac3a30",
        "type": "Role"
      }
    ],
    "resourceAppId": "00000003-0000-0000-c000-000000000000"
  }
]
`

and here, no subscriptions found 

`az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
No subscriptions found for 69af8774-d30a-450e-943d-175f7b497532.
`

and I can't list expiration dates  information

`    "appId": "69af8774-d30a-450e-943d-175f7b497532",
    "credentials": [
      {
        "created": null,
        "expires": null,
        "name": null
      }
    ]
  },` 

I've set permissions : 
![2023-01-09-134229_1140x778_scrot](https://user-images.githubusercontent.com/13317256/211311082-8f30d8f2-38ab-4a5c-b46b-c7c63478631e.png)

and secret : 
![2023-01-09-134254_1123x603_scrot](https://user-images.githubusercontent.com/13317256/211311144-c847d82c-cfb2-4a77-9979-8ca45ba476b0.png)

Thanks.

**Comment by mkoertgen** [comment]
Hi @noway75 ,

That looks weird. Not sure, I can help you with this.

**Comment by noway75** [comment]
Hi @mkoertgen,

I think on azure side it's ok, how can I check it on app side ? thanks.

**Comment by mkoertgen** [comment]
Maybe try using `--debug` with the azure cli. This will give some more diagnostics output of the intermediate REST API requests/responses that are made under the hood, cf.
- https://github.com/mkoertgen/azure-app-exporter/blob/main/_docs/references.md#azure-cli

**Comment by noway75** [comment]
When I call : 
`curl http://0.0.0.0:8000/api/apps/`    

I've this error : 
`File "azure-app-exporter/src/services/azure_app_service.py", line 31, in get_all
    self.observe(apps)
File "azure-app-exporter/src/services/azure_app_service.py", line 60, in observe
 expiry: Optional[datetime] = min(map(lambda c: c.expires, app.credentials))
expiry: Optional[datetime] = min(map(lambda c: c.expires, app.credentials))
ValueError: min() arg is an empty sequence`

**Comment by noway75** [comment]
@mkoertgen 

With this patch it's ok :

```     @staticmethod
    def observe(apps: List[AppRegistration]):
        for app in apps:
            if app.credentials:
                expiry: Optional[datetime] = min(map(lambda c: c.expires, app.credentials))
            if expiry:
               APP_EXPIRY.labels(app_id=app.id).set(int(expiry.timestamp()))

**Comment by mkoertgen** [comment]
Ah, well spotted. The expiry could be optional, so the code should be more robust. Great, thanks.

Concerning your question why only 6 of 50 apps are listed: This is probably related to the OData-response that is made under the hood.

**Comment by spiralday** [comment]
Hi @noway75 ,

I am facing the same issues you listed in the start of this error, mind sharing how did you solved it? I configured everything same as you did and also getting null.
